### ISSUE TITLE
Bug with xrefs implementation

### ISSUE THREAD

**Issue by dosumis** [balhoff/dosdp-scala#14]
`dosdp-scala generate --obo-prefixes=true --template=design_patterns/validated_patterns/activator_activity.yaml --infile=pattern_implementation_tsv/activator_activity.tsv --outfile=activator_activity.ofn --ontology=../go-simple.obo`

[activator_activity.yaml](https://gist.github.com/dosumis/4cd66d714e15c3862cc08ddadc3d98e7)

[activator_activity.tsv](https://github.com/geneontology/go-ontology/blob/master/src/pattern_implementation_tsv/activator_activity.tsv)

BUG: def_dbxrefs end up like this:

GOC:BHF,GOC:dph,GOC:tb

>

![image](https://cloud.githubusercontent.com/assets/112839/26500295/4af14f6c-422d-11e7-8b85-b636dc78336d.png)

Looks like string gets cast to a uniq'd list of characters.

**Comment by dosumis** [comment]
Note - need clear spec for TSVs.   I've assumed comma delimited in this case.

**Comment by balhoff** [comment]
I was using pipe; switched to comma. Also, the pipe was accidentally being treated as a regex.
