### ISSUE TITLE
Having issues querying ecto

### ISSUE THREAD

**Issue by cmungall** [balhoff/dosdp-scala#3]
(excuse brevity)

I tried the exposure_to_radiation.yaml pattern from ecto.

The pattern has a slash in its name, which makes its way into variables, so I hand removed these

I also removed the subClassOf* constraint, since this uses axioms in an import chain (trivial to merge I know...)

I also tried removing the filter, giving:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?radiation_exposure ?stressor
WHERE {
?radiation_exposure owl:equivalentClass ?8a2a063ecf4a4fc1919395b5076b01e9 .
?8a2a063ecf4a4fc1919395b5076b01e9 owl:intersectionOf/rdf:rest*/rdf:first <http://purl.obolibrary.org/obo/ExO:0000002> .
?8a2a063ecf4a4fc1919395b5076b01e9 owl:intersectionOf/rdf:rest*/rdf:first ?4fa6da64b15e4932ba8450b6a847034b .
?8a2a063ecf4a4fc1919395b5076b01e9 owl:intersectionOf/rdf:rest/rdf:rest rdf:nil .
?4fa6da64b15e4932ba8450b6a847034b owl:onProperty <http://purl.obolibrary.org/obo/RO:0002233> .
?4fa6da64b15e4932ba8450b6a847034b owl:someValuesFrom ?stressor .
}
```

no luck:

```
$ arq --query z.rq --data ecto.owl

---------------------------------
| radiation_exposure | stressor |
=================================
---------------------------------
```

**Comment by balhoff** [comment]
I haven't been able to test yet, but I guess it might be the `http://purl.obolibrary.org/obo/ExO:0000002` (note the colon). The code might need more clever IRI expansion. Right now if it doesn't start with `http`, then it just prepends `http://purl.obolibrary.org/obo/`.

**Comment by balhoff** [comment]
Oh also `http://purl.obolibrary.org/obo/RO:0002233`. If you change both it does work.

**Comment by balhoff** [comment]
I opened an [issue over at DOSDP](https://github.com/dosumis/dead_simple_owl_design_patterns/issues/21) that would help address this problem.

**Comment by cmungall** [comment]
oh yes, rather obvious I see it now!
